# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Good Deed Books API to Azure Web App - gdbapi

on:
  push:
    branches:
      - endpoint_sahil
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Install dotnet-ef tool
        run: |
          dotnet tool install --global dotnet-ef
          echo "++++ dotnet-ef version"
          dotnet ef --version

      - name: Build with dotnet
        run: |
          echo "++++ dotnet build"
          dotnet build --configuration Release

      - name: Add migrations
        run: |
          echo "++++ current directory"
          pwd
          echo "++++ add ApplicationIdentityDbContext migration M1"
          dotnet ef migrations add M1 --project ./src/Api/ --startup-project ./src/Api/Api.csproj --msbuildprojectextensionspath .build/obj/Api/ --context ApplicationIdentityDbContext --output-dir Data/Migrations/IdentityDb
          echo "++++ add ApiDbContext migration M2"
          dotnet ef migrations add M2 --project ./src/Api/ --startup-project ./src/Api/Api.csproj --msbuildprojectextensionspath .build/obj/Api/ --context ApiDbContext --output-dir Data/Migrations/ApiDb
          echo "++++ contents of ./src/Api/Data/Migrations/IdentityDb"
          ls ./src/Api/Data/Migrations/IdentityDb
          echo "++++ contents of ./src/Api/Data/Migrations/ApiDb"
          ls ./src/Api/Data/Migrations/ApiDb

      - name: dotnet publish
        run: |
          echo "++++ contents of dotnet publish ./src/Api/Api.csproj"
          dotnet publish ./src/Api/Api.csproj -f net8.0 -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A17E281C175C4E629A76134AA823BAC5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_258CF23452C24D9795BD94B25EF50B73 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9375B274C69740D39F4770D5D433E8B1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gdbapi'
          slot-name: 'Production'
          package: .
          
