# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - goodbooksapi

on:
  push:
    branches:
      - endpoint_sahil
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Install dotnet-ef tool
        run: |
          dotnet tool install --global dotnet-ef
          echo "++++ dotnet-ef version"
          dotnet ef --version
            
      - name: Build with dotnet
        run: |
          echo "++++ dotnet restore"
          dotnet restore
          echo "++++ dotnet build"
          dotnet build --configuration Release
      
      - name: Add migrations
        run: |
          echo "++++ current directory"
          pwd
          echo "++++ add ApplicationIdentityDbContext migration M1"
          dotnet ef migrations add M1 --project ./src/Api/ --startup-project ./src/Api/Api.csproj --msbuildprojectextensionspath .build/obj/Api/ --context ApplicationIdentityDbContext --output-dir Data/Migrations/IdentityDb
          echo "++++ add ApiDbContext migration M2"
          dotnet ef migrations add M2 --project ./src/Api/ --startup-project ./src/Api/Api.csproj --msbuildprojectextensionspath .build/obj/Api/ --context ApiDbContext --output-dir Data/Migrations/ApiDb
          echo "++++ contents of ./src/Api/Data/Migrations/IdentityDb"
          ls ./src/Api/Data/Migrations/IdentityDb
          echo "++++ contents of ./src/Api/Data/Migrations/ApiDb"
          ls ./src/Api/Data/Migrations/ApiDb

      - name: dotnet publish
        run: |
          echo "++++ contents of dotnet publish ./src/Api.Api.proj"
          dotnet publish ./src/Api.Api.proj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_543326D87AEF459D91E15D756166A5AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D57EB2BACAA54EE2AB97F696E8E99A4B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3C797712E9A047958FF5C9BB540F0543 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'goodbooksapi'
          slot-name: 'Production'
          package: .
          
