# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Good Deed Books BLAZOR project to Azure

on:
  push:
    branches:
      - endpoint_sahil
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Replace API URL in Models/Constants.cs
        working-directory: ./src/BlazorGDB
        run: |
          echo "++++ search & replace API URL in Models/Constants.cs from http://localhost:8001 to https://goodbooksapi.azurewebsites.net"
          sed -i 's|http://localhost:8001|https://goodbooksapi.azurewebsites.net|g' ./Models/Constants.cs
          echo "++++ display contents of Models/Constants.cs after search & replace"
          cat ./Models/Constants.cs

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        working-directory: ./src/BlazorGDB
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ./src/BlazorGDB
        run: dotnet publish BlazorGDB.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: sanity check
        run: |
          echo "+++++++++++++++++++++++++ where am I? ++++++++++++++++++++++++"
          pwd
          echo "++++++++++++++++++++++++ what's in current directory? ++++++++"
          ls -al
          echo "+++++ what's in the ${{env.DOTNET_ROOT}}/myapp directory? ++++"
          ls -al ${{env.DOTNET_ROOT}}/myapp
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6A854C1CD0C74473AD2E3B9F843CC396 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_224A065E650B4D5F9EB2329B6B2F1716 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_570B031F0942445C8E479905EE706F43 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gdb-blazor'
          slot-name: 'Production'
          package: .
          