# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Good Deed Books MVC project to Azure

on:
  push:
    branches:
      - endpoint_sahil
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        # run: dotnet publish ./src/AccountGoWeb/AccountGoWeb.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
        run: dotnet publish ./src/AccountGoWeb/AccountGoWeb.csproj -c Release -o ${{runner.temp}}/myapp

      - name: Archive production artifacts
        run: |
          echo "+++++++++++++++++++++++++ where am I? ++++++++++++++++++++++++"
          pwd
          echo "+++++++++++++++++++++++++ save current directory into a variable dir ++++"
          dir=$(pwd)
          echo "+++++++++ what is in variable dir ++++++++++++++"
          echo $dir
          echo "++++++++++++++++++++++++ what's in current directory? ++++++++"
          ls -al
          echo "+++++ what's in the ${{runner.temp}}/myapp directory? ++++"
          ls -al ${{runner.temp}}/myapp
          echo "+++++ change directoiry to ${{runner.temp}}/myapp ++++"
          cd ${{runner.temp}}/myapp
          echo "+++++++++++++++++++++++++ where am I? ++++++++++++++++++++++++"
          pwd
          echo "+++++++++++++++++++++++++ compress current directory and save in $dir/my_artifact.tar.gz ++++"
          tar -czvf $dir/my_artifact.tar.gz .
          echo "+++++++++++++++++++++++++ change dir to to $dir directory ++++"
          cd $dir
          echo "+++++++++++++++++++++++++ where am I? ++++++++++++++++++++++++"
          pwd
          echo "++++++++++++++++++++++++ what's in $dir directory? ++++++++"
          ls -al

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: my_artifact.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          #client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_28108B2CCE81480BB0295B2554B37231 }}
          #tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9ED1B649A03F45E7B34C3BE1217B6BDE }}
          #subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A41842A963384E4BAB26580EEFE65E92 }}
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8B6389BB3F37413FB2483AC2574C3BCB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FD62C59DE5DC42C2A07DB8191A522348 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7076EF307FDA4C11BC99A0A7A0943794 }}

      - name: Extract artifacts
        run: |
          tar -xzvf my_artifact.tar.gz -C .

      - name: Print working directory
        run: pwd

      - name: List directory contents
        run: ls -l /home/runner/.dotnet/

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          #app-name: 'good-books'
          app-name: 'gdbmvc'
          slot-name: 'Production'
          package: .
          
